// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhvV7MZfrLq64Ikj2fLGgXNDKtWWN1vCY',
    appId: '1:255191628830:web:537aee626f9a626b82420f',
    messagingSenderId: '255191628830',
    projectId: 'kachra-seth-58d84',
    authDomain: 'kachra-seth-58d84.firebaseapp.com',
    storageBucket: 'kachra-seth-58d84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn4cq8HsEnUBG7RyICg-ixFminlC3fZhY',
    appId: '1:255191628830:android:7688c5dbe81dd30982420f',
    messagingSenderId: '255191628830',
    projectId: 'kachra-seth-58d84',
    storageBucket: 'kachra-seth-58d84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJiPQzMu_Nv2OtWmF03LJMRm4oEFLfRU',
    appId: '1:255191628830:ios:f8367260a65b8fd982420f',
    messagingSenderId: '255191628830',
    projectId: 'kachra-seth-58d84',
    storageBucket: 'kachra-seth-58d84.appspot.com',
    iosClientId: '255191628830-noj4oj44cjsg3vjg44q7j6tkfb6ak3vh.apps.googleusercontent.com',
    iosBundleId: 'com.kachraseth.app.kachrasethui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeJiPQzMu_Nv2OtWmF03LJMRm4oEFLfRU',
    appId: '1:255191628830:ios:f8367260a65b8fd982420f',
    messagingSenderId: '255191628830',
    projectId: 'kachra-seth-58d84',
    storageBucket: 'kachra-seth-58d84.appspot.com',
    iosClientId: '255191628830-noj4oj44cjsg3vjg44q7j6tkfb6ak3vh.apps.googleusercontent.com',
    iosBundleId: 'com.kachraseth.app.kachrasethui',
  );
}
